### ISSUE TITLE
Can't build OSX

### ISSUE THREAD

**Issue by hammackj** [etodd/yearning#1]
$ ./setup-mac
Good news, Blender is set up correctly on the path!
Warning: cmake-3.4.1 already installed
Warning: pkg-config-0.29 already installed
Cloning into 'src/game'...
Warning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@bitbucket.org:etodd/mkzebra_private.git' into submodule path 'src/game' failed

**Comment by etodd** [comment]
Unfortunately the private repo has a lot of critical code right now. I will go whole-hog and open source the whole game. The only blocker is that I rely heavily on Wwise, and I'm not sure how thrilled they would be about me redistributing their SDK, even though it's freely available for indies, and only includes header files, libs, and a few integration files.

Just contacted a Twitter friend at AudioKinetic. Hopefully they'll give the greenlight, maybe they'll have me add a legal notice to the README, and I'll merge the private repo.

If not, I'll have to think a little harder. Haven't got that far yet.

**Comment by hammackj** [comment]
Ah cool, I saw your "Poor Man's threading" post on reddit and wanted to try it out. The "Story-driven stealth FPS with some multiplayer elements" tag line really has me interested. =) Do you have a video or anything?

**Comment by etodd** [comment]
Glad to hear it interests you. :) No video yet, but here's a [devlog](https://forums.tigsource.com/index.php?topic=49277) with some gifs.

**Comment by etodd** [comment]
Done! Had to use Git LFS for the Wwise binaries.
