### ISSUE TITLE
Bug: Standing next to object and pressing shift

### ISSUE THREAD

**Issue by jonasmg** [etodd/yearning#4]
I was having an issue where when I would stand still beside a wall/object and press shift it would make the screen black and "respawn" me. This happened in story mode.

**Comment by etodd** [comment]
I can't replicate this one. Is there a specific place this happens?

**Comment by jonasmg** [comment]
It just happened with pretty much any wall
Video: https://www.youtube.com/watch?v=qCCsN0wpS2s
Hope you can fix it
btw i found a good handful of bugs so would you like me to post them one by one or just many in one post? :)

**Comment by etodd** [comment]
Wow, okay! Thanks for that video! That gives me some idea as to how to fix it.

Feel free to report them any way you like. If it's easier to do it all in one, that's fine with me.

Thanks again!

**Comment by etodd** [comment]
This should hopefully be fixed in the latest patch!
