### ISSUE TITLE
Can't activate robet-land-teleporter-machine bug

### ISSUE THREAD

**Issue by jonasmg** [etodd/yearning#8]
The way to activate this thing is missing, i'm not sure why. Played like normal just tried to get there fast.
<img width="1117" alt="asdfesddf" src="https://user-images.githubusercontent.com/32884785/32419366-17c76d98-c279-11e7-8487-9fb1a8348329.PNG">
I wen't in and out of the story and now it's there
<img width="945" alt="asdfesddd" src="https://user-images.githubusercontent.com/32884785/32419404-9c455f08-c279-11e7-9046-6ea9d1cbb0e1.PNG">

**Comment by etodd** [comment]
This is fixed! Patch will be in the next release. Thank you! 👍 👍
